<?php

namespace CPASimUSante\SimutoolsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PluginconfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

/**
 * Class PluginconfigRepository
 */
class PluginconfigRepository extends EntityRepository
{

}