<?php

namespace CPASimUSante\SimutoolsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use JMS\DiExtraBundle\Annotation as DI;

/**
 * PluginconfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

/**
 * Class PluginconfigRepository
 *
 * @DI\Service("simutools.service.repository.pluginconfig")
 */
class PluginconfigRepository extends EntityRepository
{

}