<?php

namespace CPASimUSante\PluginconfigBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PluginconfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 *  @DI\Service("cpasimusante.plugin.repository.pluginconfig")
 */
class PluginconfigRepository extends EntityRepository
{

}